### ISSUE TITLE
Unknown error.

### ISSUE THREAD

**Issue by michaljuris** [kepi/IcingaChromedStatus#27]
Hi,
the extension was working for me just fine till last week. Suddenly I'm getting error:

*Unknown error. Please provide more details about your config to github issue page so I can help you.*

I've tried to reinstall the extension but it doesn't help.

My setup is:
Browser: 45.0.2454.78 beta (64-bit) on Ubuntu 15.04
URL: https://zerk.uol/nagios3/cgi-bin/status.cgi

Nagios version 3.5.1

Thank you for any help or suggestion.

M.

**Comment by kepi** [comment]
Hi,
zerk.uol is some internal domain or it is supposed to be working? Can you reach status.cgi page from browser without any problem?

I didnt make any changes to extension in long time so it is probable that it will be some problem with your nagios installation. Did you upgrade nagios at time it stopped working?

**Comment by michaljuris** [comment]
I found the cause  -  It is problem with ssl certificate.

Certificate is for *zerk.uol.cz*, but I'm trying to (actually have to) access it through *zerk.uol*

Is there any workaround or would it be possible to add option to "accept any certificate"?

Thanks!

M.

**Comment by kepi** [comment]
Only right solution in this case is to install correct SSL certificate to icinga. If you have to access every time through zerk.uol, cert should have common nam to `zerk.uol`. You can create own CA which you add to Chrome as trusted and issue/install this cert or add self-signed certificate as trusted.

Another option would be to move icinga install to something like "zerk.local" and have a SAN certificate with primary domain set to "zerk.uol.cz" and additional name set to "zerk.local". I think that no CA will issue certificate for "zerk.uol" because .uol can become regular domain in future. If you will be interested in this option, I can help you with choosing correct SAN certificate, just mail me to kepi at igloonet.cz (you can write in czech ;) )

Unfortunately I think there is no possible workaround on extension side. Chrome is handling access to https and it is very strict about correct certificates.

On your side (if you cant fix certificate on server), it should be possible to install local proxy with correct self signed certificate and proxy all requests to icinga installation. You may try something like Haproxy, Burp proxy.
