### ISSUE TITLE
Unknown Error (not really)

### ISSUE THREAD

**Issue by bighippo999** [kepi/IcingaChromedStatus#29]
Hi,
The plugin says to report an issue, thought I would in case it helps anyone else but I have solved it.
Overview is reporting 'Unknown error'. The reason is my SSL certificate has expired, opening the URL in a normal tab showed this immediately.
I've seen other plugins (for weather updates and stuff) have an option to ignore SSL certificate errors. Might be a good option to add for self-signed users too.

Thanks for an excellent plugin.

**Comment by kepi** [comment]
Hi, sorry for late reply, I really miss that github doesn't send notifications of new issues to mail.

Anyway - I don't want to include such feature because I strongly belive in security and this is against everything I aim for :)

But don't worry, there are simple "workarounds"

1. currently best option of all - just get free certificate from Let's Encrypt
2. create your own authority, import it in Chrome and than issue certificates for Icinga from this authority
3. there is probably also option to install your self-signed certificate to Chrome so it will not warn.

As for your original problem. I'm not sure at the moment if I'm able to check for invalid certificate from javascript so I can let user know that there is problem he needs to resolve instead of unknown error. It would probably need some external server/api to do the checks.

At the momen't, I'm closing this as wontfix, but thanks for reporting it anyway. I appreciate any feedback.
